kind: Template
apiVersion: v1
metadata:
  name: camunda
  annotations:
    description: ""
    tags: camunda,java
    iconClass: icon-java
parameters:
  - name: SOURCE_REPOSITORY_URL
    displayName: Git Repository URL
    description: The URL of the repository with your application source code.
    value: https://github.com/gil0109/SBC_DivApps
  - name: SOURCE_REPOSITORY_REF
    displayName: Git Reference
    description: Set this to a branch name, tag or other ref of your repository if you are not using the default branch.
  - name: SOURCE_CONTEXT_DIR
    displayName: Git context directory
    description: Set this to a branch name, tag or other ref of your repository if you are not using the default branch.
    value: /pilot_apps/camunda
objects:
 -  kind: ImageStream
    apiVersion: v1
    metadata:
      name: camunda
      annotations:
        description: "Keeps track of changes in the application image"
      labels:
        app: camunda
 -  kind: BuildConfig
    apiVersion: v1
    metadata:
      name: camunda
    spec:
      failedBuildsHistoryLimit: 2
      nodeSelector: null
      output:
        to:
          kind: ImageStreamTag
          name: 'camunda:latest'
      postCommit: {}
      resources:
        limits:
          cpu: '1'
          memory: 8Gi
        requests:
          cpu: '1'
          memory: 4Gi
      runPolicy: Serial
      source:
        contextDir: ${SOURCE_CONTEXT_DIR}
        git:
          ref: ${SOURCE_REPOSITORY_REF}
          uri: ${SOURCE_REPOSITORY_URL}
        type: Git
      strategy:
        dockerStrategy:
          dockerfilePath: Dockerfile
        type: Docker
      successfulBuildsHistoryLimit: 5
      triggers:
        - type: ConfigChange